### ISSUE TITLE
`record struct`s are ignored

### ISSUE THREAD

**Issue by RReverser** [BlackWhiteYoshi/InlineComposition#3]
It seems that currently any `record struct` is completely skipped over by the generator - at least I'm not seeing anything even with `EmitCompilerGeneratedFiles`, and regular `struct`s work fine.

I can use regular `struct` as a workaround for now, but it would be nice not to worry about manually defining all the equality and hashcode checks, which is something that `record struct` provides automatically.

**Comment by BlackWhiteYoshi** [comment]
You are right, I never tested records. They were skipped because I was filtering for *ClassDeclarationSyntax* and *StructDeclarationSyntax*, but records are of type *RecordDeclarationSyntax*.
It works now with the newest version (1.3.0).
