### ISSUE TITLE
Nested types support

### ISSUE THREAD

**Issue by RReverser** [BlackWhiteYoshi/InlineComposition#5]
Ok... I know this is starting to stretch it, but could nested types be inlined as well?

If I have

```cs
[InlineBase]
internal record struct BigInt {
    public readonly struct BSATN { }
}

[Inline<BigInt>]
public readonly partial record struct Foobar { }
```

I'd expect `Foobar` to also have a nested `Foobar.BSATN` struct (with same substitutions as in the top-level struct itself), but currently it's skipped.

**Comment by RReverser** [comment]
Although I'm starting to wonder if at this point it might be easier to use a plain text template + source generator.

**Comment by BlackWhiteYoshi** [comment]
Actually, inlining nested types makes sense and it was even surprisingly simple to implement, at least the simple version with just ignoring collisions. A proper implementation has to merge all members recursively when a collision happens. But for now, I leave it as it is.

Nesting types will be inlined in the newest version (1.4.0).
